// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqN4HLFxPDEaOnZ8bTG8zEThX0KKNvRAY',
    appId: '1:271280089472:web:e99bf318395a1dc6a6b965',
    messagingSenderId: '271280089472',
    projectId: 'treenote-e1fe3',
    authDomain: 'treenote-e1fe3.firebaseapp.com',
    storageBucket: 'treenote-e1fe3.appspot.com',
    measurementId: 'G-ZFK7CMWFZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOIVzXK0pRM51S7D-_6SSSFY-mHQfsBSI',
    appId: '1:271280089472:android:0e1ea49ca781183fa6b965',
    messagingSenderId: '271280089472',
    projectId: 'treenote-e1fe3',
    storageBucket: 'treenote-e1fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr_ALvHOb5isTJVOXTYoMZn5FgYYU0G2M',
    appId: '1:271280089472:ios:ea3c8e3748b71aeaa6b965',
    messagingSenderId: '271280089472',
    projectId: 'treenote-e1fe3',
    storageBucket: 'treenote-e1fe3.appspot.com',
    iosBundleId: 'com.example.treeNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr_ALvHOb5isTJVOXTYoMZn5FgYYU0G2M',
    appId: '1:271280089472:ios:ea3c8e3748b71aeaa6b965',
    messagingSenderId: '271280089472',
    projectId: 'treenote-e1fe3',
    storageBucket: 'treenote-e1fe3.appspot.com',
    iosBundleId: 'com.example.treeNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqN4HLFxPDEaOnZ8bTG8zEThX0KKNvRAY',
    appId: '1:271280089472:web:a18bc782e1dc0238a6b965',
    messagingSenderId: '271280089472',
    projectId: 'treenote-e1fe3',
    authDomain: 'treenote-e1fe3.firebaseapp.com',
    storageBucket: 'treenote-e1fe3.appspot.com',
    measurementId: 'G-ZBHKJH680G',
  );
}
